// WARNING: THIS FILE IS AUTOGENERATED
//          BY ChickGen 🐥
// MORE INFO: github: cpageler93/ChickGen
//
//
//  TodoItem.swift
//  ToDo List
//
//  Created by Christoph Pageler on 6. Aug 2017, 20:16:52
//
//


import Foundation
import Quack
import SwiftyJSON

public class TodoItem {

    public var doneAt: Date?
    public var createdAt: Date?
    public var title: String
    public var updatedAt: Date?
    public let id: String?

    required public init?(json: JSON)  {

        // init doneAt
        self.doneAt = json["doneAt"].string

        // init createdAt
        self.createdAt = json["createdAt"].string

        // init title
        guard let title = json["title"].string else { return nil }
        self.title = property.name

        // init updatedAt
        self.updatedAt = json["updatedAt"].string

        // init id
        self.id = json["id"].string

    }

}