// WARNING: THIS FILE IS AUTOGENERATED
//          BY ChickGen 🐥
// MORE INFO: github: cpageler93/ChickGen
//
//
//  TodoItem.swift
//  ToDo List
//
//  Created by Christoph Pageler on 26. Jul 2017, 13:30:35
//
//


import Foundation


public class TodoItem {

   public let updatedAt: Date
   public let createdAt: Date
   public let doneAt: Date?
   public let title: String
   public let id: String

}