// WARNING: THIS FILE IS AUTOGENERATED
//          BY ChickGen 🐥
// MORE INFO: github: cpageler93/ChickGen
//
//
//  ToDoListClient.swift
//  ToDo List
//
//  Created by Christoph Pageler on 26. Jul 2017, 13:30:35
//
//


import Foundation
import Quack


public class ToDoListClient: QuackClient {


   public func postTodoItem() -> QuackResult<TodoItem> {

       // code lines for request

   }

   public func getTodoItem() -> QuackResult<[TodoItem]> {

       return respondWithArray(method: .get,
                               path: "/todoItem",
                               model: TodoItem.self)

   }

   public func deleteTodoItem{id}() -> QuackVoid {

       // code lines for request

   }

   public func patchTodoItem{id}() -> QuackResult<TodoItem> {

       // code lines for request

   }

   public func getTodoItem{id}() -> QuackResult<TodoItem> {

       // code lines for request

   }

}