// WARNING: THIS FILE IS AUTOGENERATED
//          BY ChickGen 🐥
// MORE INFO: github: cpageler93/ChickGen
//
//
//  ToDoListClient.swift
//  ToDo List
//
//  Created by Christoph Pageler on 26. Jul 2017, 16:08:53
//
//


import Foundation
import Quack


public class ToDoListClient: QuackClient {


   public func postTodoItem(body: TodoItem) -> QuackResult<TodoItem> {

       // code lines for request

   }

   public func getTodoItem() -> QuackResult<[TodoItem]> {

       return respondWithArray(method: .get,
                               path: "/todoItem",
                               model: TodoItem.self)

   }

   public func deleteTodoItemWithId(id: String) -> QuackVoid {

       // code lines for request

   }

   public func patchTodoItemWithId(id: String, body: TodoItem) -> QuackResult<TodoItem> {

       // code lines for request

   }

   public func getTodoItemWithId(id: String) -> QuackResult<TodoItem> {

       // code lines for request

   }

}